language: node_js
node_js:
  - "node"
#cache:
#  directories
#    - "node_modules"

jobs:
#  fast_finish: true
#  allow_failures:
#    - name: "Code Lint Checker"
  include:
#    - name: "Code Lint Checker"
#      script: npm run lint
    - name: "Automated Tests"
      script: npm run test
